select * from Activiteit
select * from Persoon
select * from Aanmelding
select * from ActiviteitCategorie
select * from ActiviteitTag
select * from ActiviteitMoment
select * from Deelnamevorm
select * from Tag
select * from ActiviteitOverzicht
select * from AanmeldStatusOverzicht
select * from A_Status
